### ISSUE TITLE
Upgrade to 7.2.0 breaks docsbuild in import error

### ISSUE THREAD

**Issue by jscheffl** [SAP/swagger-plugin-for-sphinx#518]
Our CI in Apache Airflow bumped the Swagger Plugin for Sphinx to 7.2.0 and now the docsbuild fails:

```
Traceback (most recent call last):
  File "/usr/python/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/usr/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name, package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/python/lib/python3.10/site-packages/swagger_plugin_for_sphinx/__init__.py", line 5, in <module>
    from swagger_plugin_for_sphinx._plugin import setup
  File "/usr/python/lib/python3.10/site-packages/swagger_plugin_for_sphinx/_plugin.py", line 23, in <module>
    from swagger_plugin_for_sphinx._openapi_index import (
  File "/usr/python/lib/python3.10/site-packages/swagger_plugin_for_sphinx/_openapi_index.py", line 6, in <module>
    from http import HTTPMethod
ImportError: cannot import name 'HTTPMethod' from 'http' (/usr/python/lib/python3.10/http/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/python/lib/python3.10/site-packages/sphinx/cmd/build.py", line 496, in build_main
    app = Sphinx(
  File "/usr/python/lib/python3.10/site-packages/sphinx/application.py", line 256, in __init__
    self.setup_extension(extension)
  File "/usr/python/lib/python3.10/site-packages/sphinx/application.py", line 437, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/python/lib/python3.10/site-packages/sphinx/registry.py", line 456, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension swagger_plugin_for_sphinx (exception: cannot import name 'HTTPMethod' from 'http' (/usr/python/lib/python3.10/http/__init__.py))

Extension error:
Could not import extension swagger_plugin_for_sphinx (exception: cannot import name 'HTTPMethod' from 'http' (/usr/python/lib/python3.10/http/__init__.py))
```

**To Reproduce**

See CI pipeline in https://github.com/apache/airflow/actions/runs/26684426253/job/78650800420?pr=67779

Conf: https://github.com/apache/airflow/blob/main/devel-common/src/docs/provider_conf.py

**Expected behavior**

Does not break - assume a package depedency to http is missing?

**Versions (please complete the following information):**
 
- `sphinx>=7`
- `swagger-plugin-for-sphinx>=7.1.0`

**Comment by jscheffl** [comment]
Note: Apache Airflow CI runs in Python 3.10, I see same seems to be working in Python 3.14.

According to https://docs.python.org/3/library/http.html the `HTTPMethod` was added in Python 3.11

**Comment by kasium** [comment]
Thanks for the report I'm confused that the CI did not catch it

**Comment by kasium** [comment]
Will be fixed in 7.2.1 (will be released today)

**Comment by jscheffl** [comment]
Thanks, that was quick!
